## The dataset is compiled from the 1994 Census database and contains income data.
### Data Information:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Perform data analysis using Pandas by completing the given tasks.
####

In [1]:
import pandas as pd

In [2]:
# loading the dataset
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Calculate how many men and women (attribute *sex*) are represented in this dataset.**

In [3]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. What is the average age of men (attribute *age*) across the entire dataset?**

In [4]:
data[data['sex']=='Male']['age'].mean().__round__()

39

**3. What is the proportion of United States citizens (*native-country* attribute)?**

In [5]:
data['native-country'].value_counts(normalize=True)['United-States']*100

np.float64(89.5857006848684)

**4-5. Calculate the mean and standard deviation of the age of those who earn more than 50K per year (the *salary* attribute) and those who earn less than 50K per year**

In [6]:
less_age_mean=data[data['salary']=='<=50K']['age'].mean()
less_age_std=data[data['salary']=='<=50K']['age'].std()

large_age_mean=data[data['salary']=='>50K']['age'].mean()
large_age_std=data[data['salary']=='>50K']['age'].std()


print(f'less than 50k: {int(less_age_mean),int(less_age_std)}')
print(f'larger than 50k: {int(large_age_mean),int(large_age_std)}')

less than 50k: (36, 14)
larger than 50k: (44, 10)

**6. Is it true that people who earn more than 50k have at least a higher education? (*education indicator – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate*)**

In [7]:
high_edu_count=data[data['salary']=='>50K']['education'].isin(['Bachelors','Prof-school','Assocacdm','Assoc-voc','Masters','Doctorate']).count()
total_high_50_count=len(data[data['salary']=='>50K'])

# i got 100 percent which means all of the people has higher education 
print(f'percent of people who has more salary than 50k and has high edu {100*high_edu_count/total_high_50_count}')

percent of people who has more salary than 50k and has high edu 100.0

**7. Find age statistics for each race (*race* attribute) and each gender. Use *groupby* and *describe*. Find the maximum age of males of the *Asian-Pac-Islander* race.**

In [8]:
data.groupby(['race','sex'])['age'].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

In [9]:
data[(data["race"] == "Asian-Pac-Islander") & (data["sex"] == "Male")]["age"].max()

np.int64(90)

**8. Among whom is the proportion of high-earning individuals (>50K) higher: married or single men (*marital-status* indicator)? We consider those whose *marital-status* begins with *Married* (Married-civ-spouse, Married-spouse-absent, or Married-AF-spouse) to be married; the rest are considered single.**

In [10]:

married_counts = len(data[(data['salary']=='>50K') & (data['sex']=='Male') & (data['marital-status'].str.startswith('Married',na=False))])
# we just use ~ before marital-staus filter to make it notstartwith
single_count = len(data[(data['salary']=='>50K') & (data['sex']=='Male') & (~data['marital-status'].str.startswith('Married',na=False))])
total = len(data[(data['salary']=='>50K') & (data['sex']=='Male')])

print(f'single who earns higher than 50k is about {100*single_count//total} % and married {100*married_counts//total} %')

single who earns higher than 50k is about 10 % and married 89 %

**9. What is the maximum number of hours a person works per week (hours-per-week indicator)? How many people work that many hours, and what percentage of them earn a lot?**

In [11]:
max_work_hour=data['hours-per-week'].max()

how_many_work_many = len(data[data['hours-per-week']>=max_work_hour-1])

count_who_earn_alot= len(data[(data['hours-per-week']>=max_work_hour-1) & (data['salary']=='>50K')])

count_who_earn_alot_percentage = 100*count_who_earn_alot/how_many_work_many

print(f'max work hour is {max_work_hour} and {how_many_work_many} people work such, \n and {count_who_earn_alot} people earn alot and they are {round(count_who_earn_alot_percentage,2)}% of them')

max work hour is 99 and 96 people work such,
 and 28 people earn alot and they are 29.17% of them

**10. Calculate the average working hours (*hours-per-week*) of low and high earners (*salary*) for each country (*native-country*).**

In [12]:
#unstack makes it easier to read by making it colum
data.groupby(['native-country', 'salary'])['hours-per-week'].mean().unstack().sort_values('<=50K',ascending=False)

salary                          <=50K       >50K
native-country
Thailand                    42.866667  58.333333
Dominican-Republic          42.338235  47.000000
Portugal                    41.939394  41.500000
Outlying-US(Guam-USVI-etc)  41.857143        NaN
Greece                      41.809524  50.625000
Yugoslavia                  41.600000  49.500000
Iran                        41.440000  47.500000
Cambodia                    41.416667  40.000000
France                      41.058824  50.750000
Japan                       41.000000  47.958333
Ireland                     40.947368  48.000000
England                     40.483333  44.533333
Laos                        40.375000  40.000000
?                           40.164760  45.547945
South                       40.156250  51.437500
Mexico                      40.003279  46.575758
Holand-Netherlands          40.000000        NaN
Italy                       39.625000  45.400000
Scotland                    39.444444  46.666667
Guatemala                   39.360656  36.666667
Hong                        39.142857  45.000000
Germany                     39.139785  44.977273
United-States               38.799127  45.505369
Columbia                    38.684211  50.000000
Puerto-Rico                 38.470588  39.416667
Jamaica                     38.239437  41.100000
India                       38.233333  46.475000
Poland                      38.166667  39.000000
Philippines                 38.065693  43.032787
Ecuador                     38.041667  48.750000
Cuba                        37.985714  42.440000
Canada                      37.914634  45.641026
China                       37.381818  38.900000
Vietnam                     37.193548  39.200000
Trinadad&Tobago             37.058824  40.000000
Haiti                       36.325000  42.750000
Nicaragua                   36.093750  37.500000
El-Salvador                 36.030928  45.000000
Peru                        35.068966  40.000000
Honduras                    34.333333  60.000000
Taiwan                      33.774194  46.800000
Hungary                     31.300000  50.000000

**11.Group people into age groups *young*, *adult*, *retiree*, where:**
* *young* corresponds to 16-35 years old
* *adult* - 35-70 years old
* *retiree* - 70-100 years old

**Enter the name of the appropriate age group for each person in the new AgeGroup column.**

In [13]:
data['AgeGroup'] = pd.cut(
    data['age'],
    bins=[16,35,70,100],
    labels=['young','adult','retiree']
)

**12-13. Determine the number of people earning >50K in each age group (AgeGroup column), and also output the name of the age group in which people most often earn more than 50K (>50K)**

In [14]:
data_temp = data[data['salary']=='>50K']
data_temp.groupby(['AgeGroup','salary']).size()

AgeGroup  salary
young     >50K      1705
adult     >50K      6042
retiree   >50K        94
dtype: int64

**14. Group people by employment type (the occupation column) and determine the number of people in each group. Then write a filter function, filter_func, that will return only those groups in which the average age (the age column) is 40 or less and in which all employees work more than 5 hours per week (the hours-per-week column).**

In [15]:
#size of each occupation 
print(data.groupby('occupation').size())

def filter_func(df):
    return df['age'].mean()<=40 and (df['hours-per-week']>5).all()

data.groupby('occupation').filter(filter_func)

occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
442,24,Federal-gov,191073,HS-grad,9,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,<=50K,young
1300,29,Federal-gov,301010,Some-college,10,Never-married,Armed-Forces,Not-in-family,Black,Male,0,0,60,United-States,<=50K,young
14613,39,Federal-gov,227597,HS-grad,9,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,50,United-States,<=50K,adult
16111,24,Federal-gov,287988,Bachelors,13,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,40,United-States,<=50K,young
18034,34,Federal-gov,172716,12th,8,Married-civ-spouse,Armed-Forces,Husband,White,Male,0,0,40,United-States,<=50K,young
18644,23,Federal-gov,163870,Some-college,10,Never-married,Armed-Forces,Other-relative,White,Male,0,0,40,United-States,<=50K,young
18769,30,Federal-gov,76313,HS-grad,9,Married-civ-spouse,Armed-Forces,Other-relative,Amer-Indian-Eskimo,Male,0,0,48,United-States,<=50K,young
25799,46,Federal-gov,344415,Masters,14,Married-civ-spouse,Armed-Forces,Husband,White,Male,0,1887,40,United-States,>50K,adult
32316,23,Federal-gov,173851,HS-grad,9,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,8,United-States,<=50K,young

In [ ]:
data.sort_values('')

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
17096,25,?,12285,Some-college,10,Never-married,?,Not-in-family,Amer-Indian-Eskimo,Female,0,0,20,United-States,<=50K,young
27207,23,Private,13769,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Amer-Indian-Eskimo,Male,0,0,30,United-States,<=50K,young
25743,46,Local-gov,14878,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,Philippines,>50K,adult
24012,26,Private,18827,Some-college,10,Never-married,Transport-moving,Not-in-family,White,Male,0,0,40,United-States,<=50K,young
10826,25,Private,19214,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8258,35,Private,1226583,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,52,United-States,>50K,young
15569,29,Private,1268339,HS-grad,9,Married-spouse-absent,Tech-support,Own-child,Black,Male,0,0,40,United-States,<=50K,young
16739,45,Private,1366120,Assoc-voc,11,Divorced,Other-service,Not-in-family,White,Female,0,0,8,United-States,<=50K,adult
18138,39,Private,1455435,Assoc-acdm,12,Separated,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
14449,25,Private,1484705,Some-college,10,Divorced,Exec-managerial,Unmarried,White,Female,0,0,25,United-States,<=50K,young